import { FurnitureType, type Size } from "$types/items";
import { Category } from "$types/save/1.5";

export const HatWhichNumber = new Map([
    ["Cowboy Hat", 0],
    ["Bowler Hat", 1],
    ["Top Hat", 2],
    ["Straw Hat", 3],
    ["Trucker Hat", 4],
    ["Official Cap", 5],
    ["Blue Bonnet", 6],
    ["Plum Chapeau", 7],
    ["Skeleton Mask", 8],
    ["Goblin Mask", 9],
    ["Chicken Mask", 10],
    ["Earmuffs", 11],
    ["Delicate Bow", 12],
    ["Tropiclip", 13],
    ["Butterfly Bow", 14],
    ["Hunter's Cap", 15],
    ["Trucker Hat", 16],
    ["Sailor's Cap", 17],
    ["Good Ol' Cap", 18],
    ["Fedora", 19],
    ["Cool Cap", 20],
    ["Lucky Bow", 21],
    ["Polka Bow", 22],
    ["Gnome's Cap", 23],
    ["Eye Patch", 24],
    ["Santa Hat", 25],
    ["Tiara", 26],
    ["Hard Hat", 27],
    ["Sou'wester", 28],
    ["Daisy", 29],
    ["Watermelon Band", 30],
    ["Mouse Ears", 31],
    ["Cat Ears", 32],
    ["Cowgal Hat", 33],
    ["Cowpoke Hat", 34],
    ["Archer's Cap", 35],
    ["Panda Hat", 36],
    ["Blue Cowboy Hat", 37],
    ["Red Cowboy Hat", 38],
    ["Cone Hat", 39],
    ["Living Hat", 40],
    ["Emily's Magic Hat", 41],
    ["Mushroom Cap", 42],
    ["Dinosaur Hat", 43],
    ["Totem Mask", 44],
    ["Logo Cap", 45],
    ["Wearable Dwarf Helm", 46],
    ["Fashion Hat", 47],
    ["Pumpkin Mask", 48],
    ["Hair Bone", 49],
    ["Knight's Helmet", 50],
    ["Squire's Helmet", 51],
    ["Spotted Headscarf", 52],
    ["Beanie", 53],
    ["Floppy Beanie", 54],
    ["Fishing Hat", 55],
    ["Blobfish Mask", 56],
    ["Party Hat", 57],
    ["Arcane Hat", 60],
    ["Chef's Hat", 61],
    ["Pirate Hat", 62],
    ["Flat Topped Hat", 63],
    ["Elegant Turban", 64],
    ["White Turban", 65],
    ["Garbage Hat", 66],
    ["Golden Mask", 67],
    ["Propeller Hat", 68],
    ["Bridal Veil", 69],
    ["Witch Hat", 70],
    ["Copper Pan", 71],
    ["Green Turban", 72],
    ["Magic Cowbow Hat", 73],
    ["Magic Turban", 74],
    ["Golden Helmet", 75],
    ["Deluxe Pirate Hat", 76],
    ["Pink Bow", 77],
    ["Frog Hat", 78],
    ["Small Cap", 79],
    ["Bluebird Mask", 80],
    ["Deluxe Cowboy Hat", 81],
    ["Mr. Qi's Hat", 82],
    ["Dark Cowboy Hat", 83],
    ["Radioactive Goggles", 84],
    ["Swashbuckler Hat", 85],
    ["Qi Mask", 86],
    ["Star Helmet", 87],
    ["Sunglasses", 88],
    ["Goggles", 89],
    ["Forager's Hat", 90],
    ["Tiger Hat", 91],
    ["???", 92],
    ["Warrior Helmet", 93],
]);

export const FishingRodUpgradeNumber = new Map([
    ["Bamboo Pole", 0],
    ["Training Rod", 1],
    ["Fiberglass Rod", 2],
    ["Iridium Rod", 3],
]);

export const FishingRodSpriteIndex = new Map([
    ["Bamboo Pole", 8],
    ["Training Rod", 9],
    ["Fiberglass Rod", 10],
    ["Iridium Rod", 11],
]);

// https://stardewvalleywiki.com/User:IBugOne/Item_Quality#Sell_price
export const QualityToPriceMultiplier = new Map([
    [0, 1],
    [1, 1.25],
    [2, 1.5],
    [4, 2],
]);

// https://stardewvalleywiki.com/User:IBugOne/Item_Quality#Healing_effect
export const QualityToEdibilityMultiplier = new Map([
    [0, 1],
    [1, 1.40],
    [2, 1.80],
    [4, 2.60],
]);

// TODO: I don't know what items are allowed to have quality, or if there's some sort of rule.
export const CategoriesWithQuality = new Set([
    Category.Fish,
    Category.Egg,
    Category.Milk,
    Category.Cooking,
    Category.SellAtPierres,
    Category.SellAtPierresAndMarnies,
    Category.ArtisanGoods,
    Category.Syrup,
    Category.Vegetable,
    Category.Fruit,
    Category.Flower,
    Category.Forage,
]);

export const DefaultFurnitureSizes = new Map<FurnitureType, Size>([
    [FurnitureType.Chair, { width: 16, height: 32 }],
    [FurnitureType.Bench, { width: 32, height: 32 }],
    [FurnitureType.Couch, { width: 48, height: 32 }],
    [FurnitureType.Armchair, { width: 32, height: 32 }],
    [FurnitureType.Dresser, { width: 32, height: 32 }],
    [FurnitureType.LongTable, { width: 80, height: 48 }],
    [FurnitureType.Painting, { width: 32, height: 32 }],
    [FurnitureType.Lamp, { width: 16, height: 32 }],
    [FurnitureType.Decor, { width: 16, height: 32 }],
    [FurnitureType.Other, { width: 16, height: 16 }],
    [FurnitureType.Bookcase, { width: 32, height: 48 }],
    [FurnitureType.Table, { width: 32, height: 48 }],
    [FurnitureType.Rug, { width: 48, height: 32 }],
    [FurnitureType.Window, { width: 16, height: 32 }],
    [FurnitureType.Fireplace, { width: 32, height: 80 }],
    [FurnitureType.Bed, { width: 48, height: 64 }],
    [FurnitureType.Torch, { width: 16, height: 32 }],
    [FurnitureType.Sconce, { width: 16, height: 16 }],
]);

export const FurnitureTypeToNumber = new Map<FurnitureType, number>([
    [FurnitureType.Chair, 0],
    [FurnitureType.Bench, 1],
    [FurnitureType.Couch, 2],
    [FurnitureType.Armchair, 3],
    [FurnitureType.Dresser, 4],
    [FurnitureType.LongTable, 5],
    [FurnitureType.Painting, 6],
    [FurnitureType.Lamp, 7],
    [FurnitureType.Decor, 8],
    [FurnitureType.Other, 9],
    [FurnitureType.Bookcase, 10],
    [FurnitureType.Table, 11],
    [FurnitureType.Rug, 12],
    [FurnitureType.Window, 13],
    [FurnitureType.Fireplace, 14],
    [FurnitureType.Bed, 15],
    [FurnitureType.Torch, 16],
    [FurnitureType.Sconce, 17],
]);