import { SvelteSet } from "svelte/reactivity";
import type { BroadcastedMail } from "$types/save";
import { type DataProxy, Raw } from ".";

/**
 * List of known 1.6 mail flags.
 *
 * {@link https://stardewmodding.wiki.gg/wiki/Comprehensive_Mail_Flag_List}
 *
 * There are some missing flags here, such as `GotSquidFestReward_<year>_<dayOfMonth>_<#>`.
 * We may need to figure out a different abstraction for this.
 */
export enum MailFlag {
	ccDoorUnlock = "ccDoorUnlock",
	canReadJunimoText = "canReadJunimoText",
	ccBoilerRoom = "ccBoilerRoom",
	ccBulletin = "ccBulletin",
	ccCraftsRoom = "ccCraftsRoom",
	ccFishTank = "ccFishTank",
	ccPantry = "ccPantry",
	ccVault = "ccVault",
	ccIsComplete = "ccIsComplete",
	abandonedJojaMartAccessible = "abandonedJojaMartAccessible",
	ccMovieTheater = "ccMovieTheater",
	JojaMember = "JojaMember",
	jojaBoilerRoom = "jojaBoilerRoom",
	jojaCraftsRoom = "jojaCraftsRoom",
	jojaFishTank = "jojaFishTank",
	jojaPantry = "jojaPantry",
	jojaVault = "jojaVault",
	ccMovieTheaterJoja = "ccMovieTheaterJoja",
	// Gil_<monsterSlayerQuestID> = ">",
	birdieQuestFinished = "birdieQuestFinished",
	birdieQuestBegun = "birdieQuestBegun",
	gotBirdieReward = "gotBirdieReward",
	henchmanGone = "henchmanGone",
	FirstPurchase_build_crib = "FirstPurchase_build_crib",
	FirstPurchase_remove_crib = "FirstPurchase_remove_crib",
	FirstPurchase_Attic = "FirstPurchase_Attic",
	FirstPurchase_BedroomWall = "FirstPurchase_BedroomWall",
	FirstPurchase_Corner = "FirstPurchase_Corner",
	FirstPurchase_Cubby = "FirstPurchase_Cubby",
	FirstPurchase_Dining = "FirstPurchase_Dining",
	FirstPurchase_DiningRoomWall = "FirstPurchase_DiningRoomWall",
	FirstPurchase_ExtendedCorner = "FirstPurchase_ExtendedCorner",
	FirstPurchase_Southern = "FirstPurchase_Southern",
	renovation_bedroom_open = "renovation_bedroom_open",
	renovation_corner_open = "renovation_corner_open",
	renovation_cubby_open = "renovation_cubby_open",
	renovation_dining_open = "renovation_dining_open",
	renovation_diningroomwall_open = "renovation_diningroomwall_open",
	renovation_farupperroom_open = "renovation_farupperroom_open",
	renovation_extendedcorner_open = "renovation_extendedcorner_open",
	renovation_southern_open = "renovation_southern_open",
	leoMoved = "leoMoved",
	voidBookDropped = "voidBookDropped",
	cursed_doll = "cursed_doll",
	GotPerfectionStatue = "GotPerfectionStatue",
	read_a_book = "read_a_book",
	gotGoldenScythe = "gotGoldenScythe",
	OpenedSewer = "OpenedSewer",
	willyHours = "willyHours",
	MarniePetAdoption = "MarniePetAdoption",
	MarniePetRejectedAdoption = "MarniePetRejectedAdoption",
	// GotSquidFestReward_<year>_<dayOfMonth>_<#> = "<#>",
	GotCrabbingBook = "GotCrabbingBook",
	sawQiPlane = "sawQiPlane",
	rejectedPet = "rejectedPet",
	numbersEgg1 = "numbersEgg1",
	numbersEgg2 = "numbersEgg2",
	numbersEgg3 = "numbersEgg3",
	numbersEgg1_5 = "numbersEgg1.5",
	numbersEgg7 = "numbersEgg7",
	// Jas_IceCream_DF_<year> = ">",
	FizzFirstDialogue = "FizzFirstDialogue",
	DefenseBookDropped = "DefenseBookDropped",
	qiCave = "qiCave",
	gotFirstBillboardPrizeTicket = "gotFirstBillboardPrizeTicket",
	Got_Capsule = "Got_Capsule",
	gotMaxStamina = "gotMaxStamina",
	petLoveMessage = "petLoveMessage",
	GotMysteryBook = "GotMysteryBook",
	checkedMonsterBoard = "checkedMonsterBoard",
	spring_2_1 = "spring_2_1",
	// NightMarketYear<year>Day<dayOfNightMarket>_paintingSold = "_paintingSold",
	willyBoatFixed = "willyBoatFixed",
	CalderaTreasure = "CalderaTreasure",
	gotCAMask = "gotCAMask",
	// Y<year>_Cactus = "_Cactus",
	Desert_Festival_Shady_Guy = "Desert_Festival_Shady_Guy",
	Desert_Festival_Marlon = "Desert_Festival_Marlon",
	// Y<year>_Scholar = "_Scholar",
	DF_Gil_Hat = "DF_Gil_Hat",
	Checked_DF_Mine_Explanation = "Checked_DF_Mine_Explanation",
	CF_Spouse = "CF_Spouse",
	pennyQuilt0 = "pennyQuilt0",
	pennyQuilt1 = "pennyQuilt1",
	pennyQuilt2 = "pennyQuilt2",
	pennyRefurbished = "pennyRefurbished",
	willyBackRoomInvitation = "willyBackRoomInvitation",
	seenRaccoonFinishEvent = "seenRaccoonFinishEvent",
	raccoonMovedIn = "raccoonMovedIn",
	wizardJunimoNote = "wizardJunimoNote",
	checkedRaccoonStump = "checkedRaccoonStump",
	Island_Turtle = "Island_Turtle",
	// lb_<id> = ">",
	// museumCollectedReward<dataType>_<itemID>_1 = "_1",
	artifactFound = "artifactFound",
	// <MuseumRewardsDataID> = ">",
	gotPearl = "gotPearl",
	guildMember = "guildMember",
	witchStatueGone = "witchStatueGone",
	summit_cheat_event = "summit_cheat_event",
	Broken_Capsule = "Broken_Capsule",
	SecretNote20_done = "SecretNote20_done",
	checkedBulletinOnce = "checkedBulletinOnce",
	// NOQUEST_<questID> = ">",
	// NOSPECIALORDER_<specialOrderID> = ">",
	activatedJungleJunimo = "activatedJungleJunimo",
	// sawSecretSanta<year> = ">",
	savedFriends = "savedFriends",
	destroyedPods = "destroyedPods",
	killedSkeleton = "killedSkeleton",
	slimeHutchBuilt = "slimeHutchBuilt",
	Gil_Telephone = "Gil_Telephone",
	Gil_FlameSpirits = "Gil_FlameSpirits",
	WizardCatalogue = "WizardCatalogue",
	JojaThriveTerms = "JojaThriveTerms",
	// CookiePresent_year<year> = ">",
	// MilkPresent_year<year> = ">",
	pamNewChannel = "pamNewChannel",
	completedFirstBillboardQuest = "completedFirstBillboardQuest",
	skullCave = "skullCave",
	bouncerGone = "bouncerGone",
	beenToWoods = "beenToWoods",
	Visited_Island = "Visited_Island",
	Island_FirstParrot = "Island_FirstParrot",
	islandNorthCaveOpened = "islandNorthCaveOpened",
	reachedCaldera = "reachedCaldera",
	Island_UpgradeHouse = "Island_UpgradeHouse",
	IslandResort = "Island Resort",
	ClintReward = "ClintReward",
	ClintReward2 = "ClintReward2",
	junimoPlush = "junimoPlush",
	GiantQiFruitMessage = "GiantQiFruitMessage",
	GotWoodcuttingBook = "GotWoodcuttingBook",
	roeBookDropped = "roeBookDropped",
	CF_Fair = "CF_Fair",
	CF_Fish = "CF_Fish",
	CF_Sewer = "CF_Sewer",
	CF_Mines = "CF_Mines",
	CF_Statue = "CF_Statue",
	museumComplete = "museumComplete",
	EggFestival = "Egg Festival",
	IceFestival = "Ice Festival",
	grandpaPerfect = "grandpaPerfect",
	button_tut_2 = "button_tut_2",
	geodeFound = "geodeFound",
	BackpackTip = "Backpack Tip",
	gotMasteryHint = "gotMasteryHint",
	TH_LumberPile = "TH_LumberPile",
	TH_SandDragon = "TH_SandDragon",
	TH_Railroad = "TH_Railroad",
	TH_Tunnel = "TH_Tunnel",
	Henchman1 = "Henchman1",
	FullCrabPond = "FullCrabPond",
	button_tut_1 = "button_tut_1",
	SecretNote18_done = "SecretNote18_done",
	safariGuyIntro = "safariGuyIntro",
	JojaGreeting = "JojaGreeting",
	somethingToDonate = "somethingToDonate",
	somethingWasDonated = "somethingWasDonated",
	TH_MayorFridge = "TH_MayorFridge",
	AbigailInMineFirst = "AbigailInMineFirst",
	SecretNote16_done = "SecretNote16_done",
	Summit_event = "Summit_event",
	SecretNote17_done = "SecretNote17_done",
	SecretNote19_done = "SecretNote19_done",
	QiChat1 = "QiChat1",
	QiChat2 = "QiChat2",
	apeChat1 = "apeChat1",
	hasSeenAbandonedJunimoNote = "hasSeenAbandonedJunimoNote",
	seenJunimoNote = "seenJunimoNote",
	emilyFiber = "emilyFiber",
	secretNote21_done = "secretNote21_done",
	ReturnScepter = "ReturnScepter",
	addedParrotBoy = "addedParrotBoy",
	hasSeenGrandpaNote = "hasSeenGrandpaNote",
	PierreStocklist = "PierreStocklist",
	incubator = "incubator",
	ISLAND_NORTH_DIGSITE_LOAD = "ISLAND_NORTH_DIGSITE_LOAD",
	landslideDone = "landslideDone",
	lostWalnutFound = "lostWalnutFound",
	lostBookFound = "lostBookFound",
	ectoplasmDrop = "ectoplasm Drop",
	prismaticJellyDrop = "prismaticJellyDrop",
	gotMissingStocklist = "gotMissingStocklist",
	gotFirstJunimoChest = "gotFirstJunimoChest",
	clothFound = "clothFound",
	robinWell = "robinWell",
	copperFound = "copperFound",
	Bouquet = "Bouquet",
	SeaAmulet = "SeaAmulet",
	pierreBackpack = "pierreBackpack",
	foundLostTools = "foundLostTools",
	ccBulletinThankYou = "ccBulletinThankYou",
	transferredObjectsPamHouse = "transferredObjectsPamHouse",
	transferredObjectsJojaMart = "transferredObjectsJojaMart",
	Hatters = "Hatters",
	MarlonRecovery = "MarlonRecovery",
	gotMummifiedFrog = "gotMummifiedFrog",
	quest35 = "quest35",
	quest10 = "quest10",
	// <npcName>Cooking = "Cooking",
	// <npcName>Crafting = "Crafting",
	activateGoldenParrotsTonight = "activateGoldenParrotsTonight",
	willyBoatTicketMachine = "willyBoatTicketMachine",
	willyBoatAnchor = "willyBoatAnchor",
	willyBoatHull = "willyBoatHull",
	seenBoatJourney = "seenBoatJourney",
	volcanoShortcutUnlocked = "volcanoShortcutUnlocked",
	talkedToGourmand = "talkedToGourmand",
	sawParrotBoyIntro = "sawParrotBoyIntro",
	Island_N_BuriedTreasure = "Island_N_BuriedTreasure",
	Island_UpgradeBridge = "Island_UpgradeBridge",
	Island_UpgradeTrader = "Island_UpgradeTrader",
	Saw_Flame_Sprite_North_South = "Saw_Flame_Sprite_North_South",
	Saw_Flame_Sprite_North_North = "Saw_Flame_Sprite_North_North",
	Island_Secret_BuriedTreasureNut = "Island_Secret_BuriedTreasureNut",
	Island_Secret_BuriedTreasure = "Island_Secret_BuriedTreasure",
	Saw_Flame_Sprite_South = "Saw_Flame_Sprite_South",
	Island_W_Obelisk = "Island_W_Obelisk",
	Island_UpgradeHouse_Mailbox = "Island_UpgradeHouse_Mailbox",
	Island_UpgradeParrotPlatform = "Island_UpgradeParrotPlatform",
	tigerSlimeNut = "tigerSlimeNut",
	Island_W_BuriedTreasure = "Island_W_BuriedTreasure",
	Island_W_BuriedTreasure2 = "Island_W_BuriedTreasure2",
	GuildQuest = "GuildQuest",
	QiChallengeComplete = "Qi Challenge Complete",
	VisitedQuarryMine = "Visited Quarry Mine",
	reachedBottomOfHardMines = "reachedBottomOfHardMines",
	CarolinesNecklace = "Carolines Necklace",
	Island_VolcanoBridge = "Island_VolcanoBridge",
	Island_VolcanoShortcutOut = "Island_VolcanoShortcutOut",
	Saw_Flame_Sprite_Volcano = "Saw_Flame_Sprite_Volcano",
	marnieAutoGrabber = "marnieAutoGrabber",
	fishing2 = "fishing2",
	fishing6 = "fishing6",
	Beat_PK = "Beat_PK",
	JunimoKart = "JunimoKart",
	RarecrowSociety = "RarecrowSociety",
	GreenRainGus = "GreenRainGus",
	LewisStatue = "LewisStatue",
	fieldOfficeFinale = "fieldOfficeFinale",
	robinKitchenLetter = "robinKitchenLetter",
	DesertFestival = "Desert Festival",
	// <season>_<day>_<year> = ">",
	// <season>_<day> = ">",
	GalaxySword = "GalaxySword",
	// doorUnlock<NPC>[NPC2] = "]",
	krobusUnseal = "krobusUnseal",
	communityUpgradeShortcuts = "communityUpgradeShortcuts",
	hasPickedUpMagicInk = "hasPickedUpMagicInk",
	hasActivatedForestPylon = "hasActivatedForestPylon",
	FizzIntro = "FizzIntro",
	pamHouseUpgrade = "pamHouseUpgrade",
	HasUnlockedSkullDoor = "HasUnlockedSkullDoor",
	HasTownKey = "HasTownKey",
	HasSpecialCharm = "HasSpecialCharm",
	HasSkullKey = "HasSkullKey",
	HasRustyKey = "HasRustyKey",
	HasMagnifyingGlass = "HasMagnifyingGlass",
	HasMagicInk = "HasMagicInk",
	HasDarkTalisman = "HasDarkTalisman",
	HasClubCard = "HasClubCard",
	HasDwarvishTranslationGuide = "HasDwarvishTranslationGuide",
	Farm_Eternal_Parrots = "Farm_Eternal_Parrots",
	Farm_Eternal = "Farm_Eternal",
	fortuneTeller = "fortuneTeller",
	raccoonTreeFallen = "raccoonTreeFallen",
	Capsule_Broken = "Capsule_Broken",
}

/**
 * Mailbox for storing and managing mail flags.
 *
 * Mail is how SDV keeps track of player progress and events. Every single change in the game state is followed by a letter being sent to the player.
 *
 * @todo Implement behavior for "unopened" mail, etc.
 */
export class MailBox
	extends SvelteSet<MailFlag>
	implements DataProxy<BroadcastedMail>
{
	public [Raw]: BroadcastedMail;

	constructor(mail: BroadcastedMail) {
		super(mail.string as MailFlag[]);
		this[Raw] = mail;

		$effect(() => {
			this[Raw].string = Array.from(this);
		});
	}
}
