// The XML parser has no idea what should be an array and what should be an object
// This isn't a huge deal, but we can make it a little easier to work with by
// supplying a list of things we want to be arrays
export const arrayTags = new Set([
	"item",
	"GameLocations",
	// "objects",
	"Farmer",
]);
export const nestedArrayTags = new Map<string, string[]>([
	["Building", ["buildings"]],
	["Chest", ["buildingChests"]],
	["Furniture", ["furniture"]],
	["GameLocation", ["locations"]],
	[
		"Item",
		[
			"items",
			"returnedDonations",
			"junimoChest",
			"itemsLostLastDeath",
			"donatedItems",
		],
	],
	["LargeTerrainFeature", ["largeTerrainFeatures"]],
	["MarriageDialogueReference", ["currentMarriageDialogue"]],
	["NPC", ["characters"]],
	["Object", ["attachments"]],
	["Quest", ["questLog"]],
	["ResourceClump", ["resourceClumps"]],
	["Ring", ["combinedRings"]],
	["SpecialOrder", ["specialOrders", "availableSpecialOrders"]],
	[
		"enchantments",
		[
			"Item",
			"hat",
			"shirtItem",
			"pantsItem",
			"boots",
			"leftRing",
			"rightRing",
			"trinketItem",
		],
	],
	["objectives", ["SpecialOrder"]],
	[
		"previousEnchantments",
		[
			"Item",
			"hat",
			"shirtItem",
			"pantsItem",
			"boots",
			"leftRing",
			"rightRing",
			"trinketItem",
		],
	],
	["rewards", ["SpecialOrder"]],
	[
		"int",
		[
			"dialogueQuestionsAnswered",
			"professions",
			"specialItems",
			"specialBigCraftables",
			"experiencePoints",
			"eventsSeen",
			"secretNotesSeen",
			"achievements",
		],
	],
	// Ensure single-element bundle submission arrays (ArrayOfBoolean.boolean) stay arrays
	[
		"boolean",
		[
			"ArrayOfBoolean", // covers bundles submission boolean arrays
			"raccoonBundles",
		],
	],
	[
		"string",
		[
			"acceptedSpecialOrderTypes",
			"broadcastedMail",
			"checkedGarbage",
			"collectedNutTracker",
			"completedSpecialOrders",
			"constructedBuildings",
			"foundBuriedNuts",
			"mailReceived",
			"mailForTomorrow",
			"mailbox",
			"triggerActionsRun",
			"songsHeard",
			"locationsVisited",
			"worldStateIDs",
		],
	],
	[
		"item",
		[
			"cookingRecipes",
			"craftingRecipes",
			"activeDialogueEvents",
			"previousActiveDialogueEvents",
			"preSelectedItems",
			"selectedRandomElements",
			"seenParticipantsIDs",
			"participantsIDs",
			"unclaimedRewardsIDs",
			"friendshipData",
			"basicShipped",
			"mineralsFound",
			"recipesCooked",
			"fishCaught",
			"archaeologyFound",
			"giftedItems",
			"tailoredItems",
			"chestConsumedLevels",
			"cellarAssignments",
			"separateWalletItems",
		],
	],
	["Point", ["newLevels"]],
]);
